import createClient, { type ClientOptions, type Middleware } from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

interface Options {
  fetch?: typeof fetch
}

export function createClientSDK(options: Options) {
  const client = createClient<paths>({
    fetch: options.fetch || fetch,
  });

  /*
  const middleware: Middleware = {
    async onRequest({ request }) {
      request.headers.set("x-key", options.key);
      return request;
    },
    async onError({ error }) {
      return new Error("Oops, fetch failed", { cause: error });
    },
  };

  client.use(middleware);
  */

  return client
}

export type ClientSDK = ReturnType<typeof createClientSDK>
